[APPLICATION]
;; Web access port
PORT=80
;; Path to templates HTML files
RootPath=/var/techtool/thtml/
;; name of default HTML-template
RootFileName=index.thtml
RootFileName=index.thtml
;; Temporary catalog
TempPath=/tmp/

[MENU1]
MenuCaption=test
MenuCommand=/shell?cmd=ls -la /
